apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: dynatrace-logs-traces
  namespace: dynatrace
spec:
  managementState: "managed"
  envFrom:
    - secretRef:
        name: dynatrace-otelcol-dt-api-credentials
  mode: "daemonset"
  image: "ghcr.io/dynatrace/dynatrace-otel-collector/dynatrace-otel-collector:latest"
  resources:
    limits:
      memory: 1024Mi
  config:
    receivers:
      # We will add receivers during training

    processors:
      # We will add processors during training

    exporters:
      otlphttp/dynatrace:
        endpoint: "${env:DT_ENDPOINT}"
        headers:
          Authorization: "Api-Token ${env:DT_API_TOKEN}"

    service:
      pipelines:
        logs:
          receivers: [] # We will add receivers here
          processors: [] # We will add processors here
          exporters: [otlphttp/dynatrace]
