apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: custom-otel-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: registry-otel-demo
      initContainers:
        - name: wait-for-mongodb
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nc -z mongodb 27017; do echo waiting for mongodb; sleep 2; done;",
            ]
      containers:
        - name: backend
          image: registry.digitalocean.com/otel-demo/opentelemetry-demo-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: MONGODB_URI
              value: "mongodb://mongodb:27017/productdb"
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3000"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://dynatrace-logs-collector:4318/v1/logs"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: custom-otel-app
spec:
  selector:
    app: backend
  ports:
    - port: 80
      targetPort: 3000
  type: ClusterIP
