apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlite-data
  namespace: custom-otel-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: custom-otel-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: registry-otel-demo
      initContainers:
        - name: init-sqlite
          image: busybox
          command:
            [
              "sh",
              "-c",
              "mkdir -p /app/data && touch /app/data/database.sqlite && chmod -R 777 /app/data",
            ]
          volumeMounts:
            - name: sqlite-data
              mountPath: /app/data
      containers:
        - name: backend
          image: registry.digitalocean.com/otel-demo/opentelemetry-demo-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3000"
          volumeMounts:
            - name: sqlite-data
              mountPath: /app/data
      volumes:
        - name: sqlite-data
          persistentVolumeClaim:
            claimName: sqlite-data
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: custom-otel-app
spec:
  selector:
    app: backend
  ports:
    - port: 80
      targetPort: 3000
  type: ClusterIP
