apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: demo-instrumentation
spec:
  exporter:
    endpoint: http://dynatrace-logs-collector.dynatrace.svc.cluster.local:4318
  propagators:
    - tracecontext # Enables distributed tracing context
    - baggage # Enables passing metadata between services
  sampler:
    type: parentbased_traceidratio # Sampling strategy
    argument: "1" # Sample 100% of traces
  nodejs:
    env:
      - name: OTEL_NODE_ENABLED_INSTRUMENTATIONS
        value: http,express,mongodb,winston,mongoose
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: "http/protobuf"
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "http://dynatrace-logs-collector.dynatrace.svc.cluster.local:4318"
      - name: OTEL_NODE_INCLUDE_TRACE_CONTEXT
        value: "true"
      - name: OTEL_LOG_LEVEL
        value: "debug"
      - name: NODE_DEBUG
        value: "winston"
