name: Build and Push Images

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  REGISTRY: "registry.digitalocean.com/otel-demo"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 600

      - name: Set Image Tag
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build backend image
        working-directory: ./backend
        run: |
          docker build -t ${{ env.REGISTRY }}/opentelemetry-demo-backend:${{ env.IMAGE_TAG }} .
          docker push ${{ env.REGISTRY }}/opentelemetry-demo-backend:${{ env.IMAGE_TAG }}
          # Tag as latest for convenience
          docker tag ${{ env.REGISTRY }}/opentelemetry-demo-backend:${{ env.IMAGE_TAG }} ${{ env.REGISTRY }}/opentelemetry-demo-backend:latest
          docker push ${{ env.REGISTRY }}/opentelemetry-demo-backend:latest

      - name: Build frontend image
        working-directory: ./frontend
        run: |
          docker build -t ${{ env.REGISTRY }}/opentelemetry-demo-frontend:${{ env.IMAGE_TAG }} .
          docker push ${{ env.REGISTRY }}/opentelemetry-demo-frontend:${{ env.IMAGE_TAG }}
          # Tag as latest for convenience
          docker tag ${{ env.REGISTRY }}/opentelemetry-demo-frontend:${{ env.IMAGE_TAG }} ${{ env.REGISTRY }}/opentelemetry-demo-frontend:latest
          docker push ${{ env.REGISTRY }}/opentelemetry-demo-frontend:latest

      - name: Build load-generator image
        working-directory: ./load-generator
        run: |
          docker build -t ${{ env.REGISTRY }}/opentelemetry-demo-load-generator:${{ env.IMAGE_TAG }} .
          docker push ${{ env.REGISTRY }}/opentelemetry-demo-load-generator:${{ env.IMAGE_TAG }}
          # Tag as latest for convenience
          docker tag ${{ env.REGISTRY }}/opentelemetry-demo-load-generator:${{ env.IMAGE_TAG }} ${{ env.REGISTRY }}/opentelemetry-demo-load-generator:latest
          docker push ${{ env.REGISTRY }}/opentelemetry-demo-load-generator:latest
