name: Build and Push Images

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  REGISTRY: "registry.digitalocean.com/otel-demo"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 600

      - name: Set Image Tag
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build and push backend image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: |
            ${{ env.REGISTRY }}/opentelemetry-demo-backend:${{ env.IMAGE_TAG }}
            ${{ env.REGISTRY }}/opentelemetry-demo-backend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ env.REGISTRY }}/opentelemetry-demo-frontend:${{ env.IMAGE_TAG }}
            ${{ env.REGISTRY }}/opentelemetry-demo-frontend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push load-generator image
        uses: docker/build-push-action@v4
        with:
          context: ./load-generator
          push: true
          tags: |
            ${{ env.REGISTRY }}/opentelemetry-demo-load-generator:${{ env.IMAGE_TAG }}
            ${{ env.REGISTRY }}/opentelemetry-demo-load-generator:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
